"""
Static mapping of common stock tickers to the industry/sector tags used
throughout the app -- the same vocabulary as backend/committees_map.py --
so a trade can be cross-referenced against the sectors a politician's
committee assignments actually oversee.

There is no free, reliable, key-less API for ticker -> sector/industry
classification, so -- consistent with committees_map.py -- this is a
hand-curated mapping. Tickers not listed here are simply never flagged for
a potential conflict; we intentionally never guess, to avoid false
positives. It's plain Python and safe to extend -- no other code needs to
change.

Coverage: this list was built from the actual frequency of tickers seen in
real congressional trade disclosures (~32k trades from the Senate/House
Stock Watcher datasets), covering the ~500 most-traded tickers on file,
which together account for roughly two-thirds of all disclosed trades.
Includes some historical/delisted/renamed tickers (e.g. FB, RTN, CELG,
DISCA) since disclosure data goes back to ~2012 and many of those trades
are still in the dataset under their ticker at the time.

Deliberately excluded: broad-market index ETFs (SPY, QQQ, DIA, GLD, IWD,
IWF, IWN, IEMG, VIG, PFF, PSQ, VEA, VOE, etc.) -- a trade in a total-market
fund isn't meaningfully "in" any one committee's oversight sector, so
flagging it would be misleading rather than informative.
"""

TICKER_SECTORS = {
    # ---- Technology / semiconductors / internet ----
    "AAPL": ["Technology", "Consumer Products"],
    "MSFT": ["Technology"],
    "GOOGL": ["Technology", "Media", "Antitrust"],
    "GOOG": ["Technology", "Media", "Antitrust"],
    "AMZN": ["Technology", "Consumer Products", "Antitrust"],
    "META": ["Technology", "Media", "Antitrust"],
    "FB": ["Technology", "Media", "Antitrust"],  # Meta's ticker before its 2022 rename
    "NVDA": ["Technology", "Semiconductors"],
    "AMD": ["Technology", "Semiconductors"],
    "INTC": ["Technology", "Semiconductors"],
    "QCOM": ["Technology", "Semiconductors", "Telecommunications"],
    "AVGO": ["Technology", "Semiconductors"],
    "TXN": ["Technology", "Semiconductors"],
    "MU": ["Technology", "Semiconductors"],
    "CRM": ["Technology"],
    "ORCL": ["Technology"],
    "ADBE": ["Technology"],
    "IBM": ["Technology"],
    "CSCO": ["Technology", "Telecommunications"],
    "NFLX": ["Technology", "Media"],
    "TSLA": ["Technology", "Aerospace"],
    "PLTR": ["Technology", "Defense", "Cybersecurity"],
    "CRWD": ["Technology", "Cybersecurity"],
    "PANW": ["Technology", "Cybersecurity"],
    "NOW": ["Technology"],
    "SNOW": ["Technology"],
    "SHOP": ["Technology"],
    "UBER": ["Technology", "Transportation"],
    "LYFT": ["Technology", "Transportation"],
    "ABNB": ["Technology"],
    "ACN": ["Technology", "Government Services"],
    "FEYE": ["Technology", "Cybersecurity"],
    "BABA": ["Technology", "International Trade"],
    "TWTR": ["Technology", "Media", "Antitrust"],
    "ATVI": ["Technology", "Media", "Antitrust"],
    "CTSH": ["Technology"],
    "GLW": ["Technology", "Telecommunications"],
    "INTU": ["Technology", "Financial Services", "Fintech"],
    "ENTG": ["Technology", "Semiconductors"],
    "TSM": ["Technology", "Semiconductors", "International Trade"],
    "ADI": ["Technology", "Semiconductors"],
    "AMAT": ["Technology", "Semiconductors"],
    "ASML": ["Technology", "Semiconductors", "International Trade"],
    "NXPI": ["Technology", "Semiconductors"],
    "LRCX": ["Technology", "Semiconductors"],
    "KLAC": ["Technology", "Semiconductors"],
    "MRVL": ["Technology", "Semiconductors"],
    "MCHP": ["Technology", "Semiconductors"],
    "CDNS": ["Technology", "Semiconductors"],
    "OLED": ["Technology"],
    "SNDK": ["Technology", "Semiconductors"],
    "WDC": ["Technology", "Semiconductors"],
    "HPQ": ["Technology"],
    "EMC": ["Technology"],
    "RHT": ["Technology"],
    "CERN": ["Healthcare", "Technology"],
    "ADSK": ["Technology"],
    "GDDY": ["Technology"],
    "EQIX": ["Real Estate", "Technology"],
    "ANET": ["Technology"],
    "SPLK": ["Technology", "Cybersecurity"],
    "SSNC": ["Technology", "Financial Services"],
    "WDAY": ["Technology"],
    "PTON": ["Technology", "Consumer Products"],
    "FTNT": ["Technology", "Cybersecurity"],
    "CHKP": ["Technology", "Cybersecurity"],
    "AKAM": ["Technology", "Cybersecurity"],
    "IT": ["Technology"],
    "APTV": ["Technology"],
    "EBAY": ["Technology", "Antitrust"],
    "FTV": ["Technology", "Infrastructure"],
    "IRM": ["Real Estate", "Technology"],
    "PCLN": ["Technology", "Transportation"],
    "CDW": ["Technology"],
    "CGNX": ["Technology"],
    "PTC": ["Technology"],
    "SE": ["Technology"],
    "MELI": ["Technology"],
    "GPN": ["Financial Services", "Fintech"],
    "INFO": ["Financial Services", "Technology"],
    "TDOC": ["Healthcare", "Technology"],
    "MTCH": ["Technology", "Media"],
    "TTD": ["Technology", "Media"],
    "W": ["Technology", "Consumer Products"],
    "DASH": ["Technology", "Transportation"],
    "CHWY": ["Technology", "Consumer Products"],
    "CSGP": ["Real Estate", "Technology"],
    "EA": ["Technology", "Media"],
    "HQY": ["Healthcare", "Financial Services"],
    "TCEHY": ["Technology", "Media", "International Trade"],
    "SONY": ["Technology", "Media"],
    "HUYA": ["Technology", "Media"],
    "BIDU": ["Technology", "International Trade"],
    "IFNNY": ["Technology", "Semiconductors", "International Trade"],
    "FANUF": ["Technology", "Infrastructure", "International Trade"],
    "AXTA": ["Chemicals"],
    "VSAT": ["Telecommunications", "Aerospace"],
    "SPOT": ["Technology", "Media"],
    "SNAP": ["Technology", "Media"],

    # ---- Banking / financial services / fintech / insurance ----
    "JPM": ["Banking", "Financial Services"],
    "BAC": ["Banking", "Financial Services"],
    "WFC": ["Banking", "Financial Services"],
    "C": ["Banking", "Financial Services"],
    "GS": ["Banking", "Financial Services"],
    "MS": ["Banking", "Financial Services"],
    "USB": ["Banking", "Financial Services"],
    "PNC": ["Banking", "Financial Services"],
    "TFC": ["Banking", "Financial Services"],
    "SCHW": ["Banking", "Financial Services"],
    "AXP": ["Financial Services", "Banking"],
    "V": ["Financial Services", "Fintech"],
    "MA": ["Financial Services", "Fintech"],
    "PYPL": ["Financial Services", "Fintech"],
    "SQ": ["Financial Services", "Fintech"],
    "COIN": ["Financial Services", "Cryptocurrency", "Fintech"],
    "BLK": ["Financial Services"],
    "BX": ["Financial Services"],
    "KKR": ["Financial Services"],
    "FDC": ["Financial Services", "Fintech"],
    "FIS": ["Financial Services", "Fintech"],
    "FISV": ["Financial Services", "Fintech"],
    "ICE": ["Financial Services"],
    "STT": ["Financial Services", "Banking"],
    "RF": ["Banking", "Financial Services"],
    "COF": ["Banking", "Financial Services"],
    "CME": ["Financial Services", "Commodities"],
    "BK": ["Banking", "Financial Services"],
    "MMC": ["Insurance", "Financial Services"],
    "IVZ": ["Financial Services"],
    "EFX": ["Financial Services", "Technology"],
    "DFS": ["Banking", "Financial Services", "Fintech"],
    "SYF": ["Banking", "Financial Services", "Fintech"],
    "VRSK": ["Insurance", "Technology"],
    "BKI": ["Financial Services", "Technology", "Real Estate"],
    "AMP": ["Financial Services"],
    "NDAQ": ["Financial Services"],
    "SPGI": ["Financial Services"],
    "BRK-B": ["Financial Services", "Insurance"],
    "LPLA": ["Financial Services"],
    "TROW": ["Financial Services"],
    "BEN": ["Financial Services"],
    "ARCC": ["Financial Services"],
    "HTGC": ["Financial Services"],
    "MSCI": ["Financial Services"],
    "ALLY": ["Banking", "Financial Services"],
    "CIT": ["Banking", "Financial Services"],
    "FHN": ["Banking", "Financial Services"],
    "SNV": ["Banking", "Financial Services"],
    "MTB": ["Banking", "Financial Services"],
    "FMAO": ["Banking", "Financial Services"],
    "PFS": ["Banking", "Financial Services"],
    "JKHY": ["Financial Services", "Fintech"],
    "FLT": ["Financial Services", "Fintech"],
    "AMG": ["Financial Services"],
    "BBVA": ["Banking", "Financial Services", "International Trade"],
    "UBS": ["Banking", "Financial Services", "International Trade"],
    "TD": ["Banking", "Financial Services", "International Trade"],
    "HDB": ["Banking", "Financial Services", "International Trade"],
    "BOIVF": ["Banking", "Financial Services", "International Trade"],
    # Insurance
    "AIG": ["Insurance"],
    "PGR": ["Insurance"],
    "MET": ["Insurance"],
    "PRU": ["Insurance"],
    "TRV": ["Insurance"],
    "ALL": ["Insurance"],
    "AON": ["Insurance"],
    "AJG": ["Insurance"],
    "BRO": ["Insurance"],
    "MKL": ["Insurance"],
    "WTW": ["Insurance", "Financial Services"],
    "CB": ["Insurance"],
    "AFL": ["Insurance"],
    "CNC": ["Healthcare", "Insurance"],
    "ANTM": ["Healthcare", "Insurance"],
    "ELV": ["Healthcare"],
    # Real Estate
    "PLD": ["Real Estate"],
    "SPG": ["Real Estate"],
    "O": ["Real Estate"],
    "PSA": ["Real Estate"],
    "DLR": ["Real Estate", "Technology"],
    "AMT": ["Real Estate", "Telecommunications"],
    "CCI": ["Real Estate", "Telecommunications"],
    "NLY": ["Real Estate", "Financial Services"],
    "VTR": ["Real Estate", "Healthcare"],
    "EXR": ["Real Estate"],
    "HHC": ["Real Estate"],
    "DHI": ["Real Estate", "Construction"],

    # ---- Healthcare / Pharma / Biotech ----
    "JNJ": ["Healthcare", "Pharmaceuticals"],
    "PFE": ["Healthcare", "Pharmaceuticals"],
    "MRK": ["Healthcare", "Pharmaceuticals"],
    "ABBV": ["Healthcare", "Pharmaceuticals"],
    "LLY": ["Healthcare", "Pharmaceuticals"],
    "BMY": ["Healthcare", "Pharmaceuticals"],
    "AMGN": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "GILD": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "BIIB": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "REGN": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "VRTX": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "MRNA": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "UNH": ["Healthcare", "Government Services"],
    "CVS": ["Healthcare", "Pharmaceuticals"],
    "CI": ["Healthcare"],
    "HUM": ["Healthcare"],
    "ISRG": ["Healthcare"],
    "MDT": ["Healthcare"],
    "ABT": ["Healthcare"],
    "TMO": ["Healthcare", "Biotechnology"],
    "DHR": ["Healthcare", "Biotechnology"],
    "CELG": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "AGN": ["Healthcare", "Pharmaceuticals"],
    "ACT": ["Healthcare", "Pharmaceuticals"],
    "MYL": ["Healthcare", "Pharmaceuticals"],
    "GSK": ["Healthcare", "Pharmaceuticals"],
    "AZN": ["Healthcare", "Pharmaceuticals"],
    "NVS": ["Healthcare", "Pharmaceuticals"],
    "RHHBY": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "MCK": ["Healthcare", "Pharmaceuticals"],
    "ESRX": ["Healthcare", "Pharmaceuticals"],
    "WBA": ["Healthcare", "Pharmaceuticals", "Consumer Products"],
    "BDX": ["Healthcare"],
    "BAX": ["Healthcare"],
    "BSX": ["Healthcare"],
    "SYK": ["Healthcare"],
    "ZBH": ["Healthcare"],
    "ZTS": ["Healthcare", "Pharmaceuticals", "Agriculture"],
    "ILMN": ["Healthcare", "Biotechnology"],
    "ALXN": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "BMRN": ["Healthcare", "Pharmaceuticals", "Biotechnology"],
    "EDIT": ["Healthcare", "Biotechnology"],
    "EXAS": ["Healthcare", "Biotechnology"],
    "CRL": ["Healthcare", "Biotechnology"],
    "CYRX": ["Healthcare", "Biotechnology"],
    "DXCM": ["Healthcare"],
    "EW": ["Healthcare"],
    "ALGN": ["Healthcare"],
    "HCA": ["Healthcare"],
    "LH": ["Healthcare"],
    "IQV": ["Healthcare", "Pharmaceuticals"],
    "HSIC": ["Healthcare"],
    "TFX": ["Healthcare"],
    "KVUE": ["Healthcare", "Consumer Products"],
    "ELAN": ["Healthcare", "Pharmaceuticals", "Agriculture"],
    "CAH": ["Healthcare", "Pharmaceuticals"],

    # ---- Energy / Oil & Gas / Utilities ----
    "XOM": ["Energy", "Oil & Gas"],
    "CVX": ["Energy", "Oil & Gas"],
    "COP": ["Energy", "Oil & Gas"],
    "SLB": ["Energy", "Oil & Gas"],
    "OXY": ["Energy", "Oil & Gas"],
    "KMI": ["Energy", "Oil & Gas"],
    "WMB": ["Energy", "Oil & Gas"],
    "NEE": ["Energy", "Utilities"],
    "DUK": ["Energy", "Utilities"],
    "SO": ["Energy", "Utilities"],
    "D": ["Energy", "Utilities"],
    "EXC": ["Energy", "Utilities", "Nuclear"],
    "AEP": ["Energy", "Utilities"],
    "SRE": ["Energy", "Utilities"],
    "PCG": ["Energy", "Utilities"],
    "ET": ["Energy", "Oil & Gas"],
    "ETP": ["Energy", "Oil & Gas"],
    "ETE": ["Energy", "Oil & Gas"],
    "AM": ["Energy", "Oil & Gas"],
    "NGL": ["Energy", "Oil & Gas"],
    "OKE": ["Energy", "Oil & Gas"],
    "DVN": ["Energy", "Oil & Gas"],
    "EPD": ["Energy", "Oil & Gas"],
    "WPX": ["Energy", "Oil & Gas"],
    "BP": ["Energy", "Oil & Gas"],
    "PAA": ["Energy", "Oil & Gas"],
    "MPLX": ["Energy", "Oil & Gas"],
    "PSX": ["Energy", "Oil & Gas"],
    "PSXP": ["Energy", "Oil & Gas"],
    "GEL": ["Energy", "Oil & Gas"],
    "PXD": ["Energy", "Oil & Gas"],
    "WES": ["Energy", "Oil & Gas"],
    "APC": ["Energy", "Oil & Gas"],
    "APA": ["Energy", "Oil & Gas"],
    "HAL": ["Energy", "Oil & Gas"],
    "WPZ": ["Energy", "Oil & Gas"],
    "MPC": ["Energy", "Oil & Gas"],
    "VLO": ["Energy", "Oil & Gas"],
    "VLP": ["Energy", "Oil & Gas"],
    "SU": ["Energy", "Oil & Gas"],
    "ENB": ["Energy", "Oil & Gas"],
    "MMP": ["Energy", "Oil & Gas"],
    "SHLX": ["Energy", "Oil & Gas"],
    "TRGP": ["Energy", "Oil & Gas"],
    "TRP": ["Energy", "Oil & Gas"],
    "ENLC": ["Energy", "Oil & Gas"],
    "ENBL": ["Energy", "Oil & Gas"],
    "CEQP": ["Energy", "Oil & Gas"],
    "USAC": ["Energy", "Oil & Gas"],
    "BPL": ["Energy", "Oil & Gas"],
    "LNG": ["Energy", "Oil & Gas"],
    "EOG": ["Energy", "Oil & Gas"],
    "FANG": ["Energy", "Oil & Gas"],
    "CLR": ["Energy", "Oil & Gas"],
    "PAGP": ["Energy", "Oil & Gas"],
    "TOT": ["Energy", "Oil & Gas"],
    "ARLP": ["Energy", "Mining"],
    "FSLR": ["Energy", "Technology"],
    "AWK": ["Utilities"],
    "ES": ["Energy", "Utilities"],
    "LNT": ["Energy", "Utilities"],
    "PPL": ["Energy", "Utilities"],
    "XEL": ["Energy", "Utilities"],
    "NWN": ["Energy", "Utilities"],

    # ---- Aerospace / Defense ----
    "LMT": ["Defense", "Aerospace", "Military Contractors"],
    "RTX": ["Defense", "Aerospace", "Military Contractors"],
    "NOC": ["Defense", "Aerospace", "Military Contractors"],
    "GD": ["Defense", "Aerospace", "Military Contractors"],
    "LHX": ["Defense", "Aerospace", "Military Contractors"],
    "HII": ["Defense", "Military Contractors"],
    "TXT": ["Defense", "Aerospace"],
    "BA": ["Aerospace", "Defense"],
    "UTX": ["Defense", "Aerospace", "Military Contractors"],
    "RTN": ["Defense", "Aerospace", "Military Contractors"],
    "TDG": ["Aerospace", "Defense", "Military Contractors"],
    "BWXT": ["Defense", "Nuclear", "Military Contractors"],
    "HXL": ["Aerospace", "Defense"],
    "CACI": ["Defense", "Government Contractors"],
    "FLIR": ["Defense", "Technology"],

    # ---- Telecommunications / Media ----
    "T": ["Telecommunications"],
    "VZ": ["Telecommunications"],
    "TMUS": ["Telecommunications"],
    "CMCSA": ["Telecommunications", "Media"],
    "CHTR": ["Telecommunications", "Media"],
    "DIS": ["Media"],
    "WBD": ["Media"],
    "PARA": ["Media"],
    "FOXA": ["Media"],
    "FOX": ["Media"],
    "NWSA": ["Media"],
    "DISCA": ["Media"],
    "TWX": ["Media"],
    "CBS": ["Media"],
    "VIAC": ["Media"],
    "LYV": ["Media"],
    "LGF-B": ["Media"],
    "CTL": ["Telecommunications"],
    "VOD": ["Telecommunications", "International Trade"],
    "CHL": ["Telecommunications", "International Trade"],
    "ADT": ["Homeland Security", "Technology"],

    # ---- Industrials / Transportation / Aerospace-adjacent ----
    "UNP": ["Transportation", "Railroads"],
    "CSX": ["Transportation", "Railroads"],
    "NSC": ["Transportation", "Railroads"],
    "DAL": ["Transportation", "Airlines"],
    "UAL": ["Transportation", "Airlines"],
    "AAL": ["Transportation", "Airlines"],
    "LUV": ["Transportation", "Airlines"],
    "FDX": ["Transportation", "Shipping"],
    "UPS": ["Transportation", "Shipping"],
    "CAT": ["Infrastructure", "Construction"],
    "DE": ["Agriculture", "Infrastructure"],
    "HON": ["Aerospace", "Technology"],
    "GE": ["Aerospace", "Energy"],
    "MMM": ["Healthcare", "Infrastructure"],
    "EMR": ["Infrastructure", "Construction"],
    "ETN": ["Energy", "Infrastructure"],
    "JCI": ["Infrastructure", "Energy"],
    "ITW": ["Infrastructure", "Construction"],
    "ROK": ["Infrastructure", "Technology"],
    "ROP": ["Technology", "Healthcare"],
    "DOV": ["Infrastructure"],
    "PH": ["Infrastructure", "Aerospace"],
    "SWK": ["Infrastructure", "Consumer Products"],
    "IR": ["Infrastructure"],
    "AOS": ["Infrastructure"],
    "FAST": ["Infrastructure", "Construction"],
    "GWW": ["Infrastructure", "Construction"],
    "TT": ["Infrastructure", "Energy"],
    "CARR": ["Infrastructure", "Energy"],
    "PWR": ["Infrastructure", "Energy"],
    "URI": ["Construction", "Infrastructure"],
    "VMC": ["Infrastructure", "Construction"],
    "USG": ["Infrastructure", "Construction"],
    "WCC": ["Infrastructure"],
    "TEL": ["Technology", "Infrastructure"],
    "HUBB": ["Infrastructure", "Energy"],
    "AYI": ["Infrastructure"],
    "EXPE": ["Technology", "Transportation"],
    "BKNG": ["Technology", "Transportation"],
    "CCL": ["Transportation"],
    "MAR": ["Consumer Products"],
    "KMX": ["Consumer Products"],
    "AZO": ["Consumer Products"],
    "ORLY": ["Consumer Products"],
    "HOG": ["Consumer Products"],
    "F": ["Consumer Products"],
    "GM": ["Consumer Products"],
    "DAIUF": ["Consumer Products", "International Trade"],

    # ---- Consumer / Retail / Food & Beverage / Agriculture ----
    "WMT": ["Consumer Products"],
    "COST": ["Consumer Products"],
    "TGT": ["Consumer Products"],
    "HD": ["Consumer Products", "Infrastructure"],
    "LOW": ["Consumer Products", "Infrastructure"],
    "MCD": ["Consumer Products", "Food & Beverage"],
    "SBUX": ["Consumer Products", "Food & Beverage"],
    "KO": ["Food & Beverage", "Consumer Products"],
    "PEP": ["Food & Beverage", "Consumer Products"],
    "MO": ["Consumer Products"],
    "PM": ["Consumer Products"],
    "PG": ["Consumer Products"],
    "CL": ["Consumer Products"],
    "KHC": ["Food & Beverage", "Consumer Products", "Agriculture"],
    "GIS": ["Food & Beverage", "Agriculture"],
    "ADM": ["Agriculture", "Commodities"],
    "BG": ["Agriculture", "Commodities"],
    "MOS": ["Agriculture", "Commodities"],
    "CF": ["Agriculture", "Commodities"],
    "TJX": ["Consumer Products"],
    "KR": ["Food & Beverage", "Consumer Products", "Agriculture"],
    "NKE": ["Consumer Products"],
    "URBN": ["Consumer Products"],
    "HBI": ["Consumer Products"],
    "GPK": ["Consumer Products"],
    "EL": ["Consumer Products"],
    "VFC": ["Consumer Products"],
    "CLX": ["Consumer Products"],
    "DG": ["Consumer Products"],
    "MDLZ": ["Food & Beverage", "Consumer Products"],
    "M": ["Consumer Products"],
    "UL": ["Consumer Products", "Food & Beverage"],
    "DEO": ["Food & Beverage", "Consumer Products"],
    "SYY": ["Food & Beverage"],
    "NSRGY": ["Food & Beverage", "Consumer Products"],
    "HSY": ["Food & Beverage"],
    "K": ["Food & Beverage"],
    "SJM": ["Food & Beverage"],
    "TAP": ["Food & Beverage"],
    "CAG": ["Food & Beverage"],
    "CMG": ["Food & Beverage", "Consumer Products"],
    "DLTR": ["Consumer Products"],
    "TSCO": ["Consumer Products", "Agriculture"],
    "WFM": ["Food & Beverage", "Consumer Products"],
    "AAN": ["Consumer Products"],
    "WRK": ["Consumer Products"],
    "STZ": ["Food & Beverage", "Consumer Products"],
    "BUD": ["Food & Beverage", "Consumer Products"],
    "CHD": ["Consumer Products"],
    "ROST": ["Consumer Products"],
    "LULU": ["Consumer Products"],
    "LW": ["Food & Beverage", "Agriculture"],
    "SCI": ["Consumer Products"],
    "BLL": ["Consumer Products"],
    "CCK": ["Consumer Products"],
    "HAS": ["Consumer Products"],
    "JWN": ["Consumer Products"],
    "DPZ": ["Food & Beverage", "Consumer Products"],
    "MKC": ["Food & Beverage"],
    "MNST": ["Food & Beverage", "Consumer Products"],
    "UA": ["Consumer Products"],
    "ULTA": ["Consumer Products"],
    "PLNT": ["Consumer Products"],
    "YUM": ["Food & Beverage", "Consumer Products"],
    "DRI": ["Food & Beverage", "Consumer Products"],
    "FMX": ["Food & Beverage", "International Trade"],
    "ADDYY": ["Consumer Products", "International Trade"],
    "LVMUY": ["Consumer Products", "International Trade"],

    # ---- Chemicals / Materials / Mining ----
    "DD": ["Chemicals"],
    "DOW": ["Chemicals"],
    "DWDP": ["Chemicals"],
    "LIN": ["Chemicals"],
    "PX": ["Chemicals"],
    "APD": ["Chemicals", "Energy"],
    "ECL": ["Chemicals", "Environment"],
    "SHW": ["Chemicals", "Consumer Products"],
    "PPG": ["Chemicals"],
    "LYB": ["Chemicals"],
    "RPM": ["Chemicals"],
    "IFF": ["Chemicals", "Consumer Products"],
    "WLK": ["Chemicals"],
    "ALB": ["Chemicals", "Mining"],
    "AXLL": ["Chemicals"],
    "CTVA": ["Agriculture", "Chemicals"],
    "NEM": ["Mining"],
    "FCX": ["Mining"],
    "GOLD": ["Mining"],
    "AA": ["Mining"],
    "RIO": ["Mining", "International Trade"],
    "IP": ["Infrastructure", "Consumer Products"],

    # ---- Gaming ----
    "LVS": ["Gaming & Casinos"],
    "WYNN": ["Gaming & Casinos"],
    "MGM": ["Gaming & Casinos"],
    "DKNG": ["Gaming & Casinos", "Technology"],
    "CZR": ["Gaming & Casinos"],
}

def get_sectors_for_ticker(ticker):
    """Returns a list of sector tags for a stock ticker, or [] if we don't
    have a mapping for it (in which case it's simply never flagged -- we
    never guess, to avoid false positives)."""
    if not ticker:
        return []
    return TICKER_SECTORS.get(ticker.strip().upper(), [])
